Portfolio desktop version
PNdunguMaina/My-personal-portfolio pull request #1
Opened 2022-06-03 08:54 UTC by PNdunguMaina

In this project, I did the following:

- Added the microverseinc/readme template
- Added the HTML/CSS linters checkers files
- Added the .gitignorefile
- Added the .png file for the images in Figma template 4
- Added the index.html file
- Added the styles.css file

2022-06-03 10:26 UTC, roshan-bajgain requested changes
Hi @PNdunguMaina, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/KG5KpLlr1UEPvwgkiM/giphy.gif"/>
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 10:26 UTC, roshan-bajgain commented on styles.css
> +  width: 241px;
- [ ] Kindly use media queries for the Desktop breakpoint in the CSS file. (the value for the min-width property should be in the range of 768px or wider). In the past you made a mobile version now it's time to make a desktop version and you need to use media queries for that.

2022-06-03 10:26 UTC, roshan-bajgain commented on index.html
> +        </div>
- [ ] The separation between the links is not adjustable kindly make changes and kindly wrap this content with a ul tag, and for each use li tag and wrap this li tag with a tag as this is the link.
### your design
![his](https://user-images.githubusercontent.com/81727988/171832829-d66d0414-74c5-4c59-80b2-2785937afaa2.png)
### Figma design
![fgima](https://user-images.githubusercontent.com/81727988/171832890-353f69de-9564-46be-ba03-2312afb1dbf8.png)

2022-06-03 10:26 UTC, roshan-bajgain commented on index.html
> +          <li>
- [ ] Your background is missing this small content kindly implement it.
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/171833303-49ad2d03-bf2a-4baa-b322-bf5d6aab313b.png)

2022-06-03 10:26 UTC, roshan-bajgain commented on index.html
> +          <li>
- [ ] I would suggest you that make the spacing after software developer you have large spacing after your name kindly implement it.
- [ ] After this text there is gray line for separation that line is has too width kindly adjust it
### your design
![his](https://user-images.githubusercontent.com/81727988/171833865-36341912-0ff6-4220-aaf6-1dea9901f217.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/171833908-38e37ad2-cb23-4583-9118-949b9d01f0bf.png)

2022-06-03 10:26 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] There is too much spacing with `li` tag and it is separated with a small line as shown in the figure kindly implement it.
- [ ] Your are having black border in the see project buttons kindly implement it.
- [ ] Kinldy implement it in all the section
### your design
![his](https://user-images.githubusercontent.com/81727988/171835023-5e4244ae-97c9-4a96-a14b-2f288bbb775c.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/171835044-3e4f1d25-36c4-4b23-a6da-67c2e323e61f.png)

2022-06-03 10:26 UTC, roshan-bajgain commented on index.html
> +        </p>
- [ ] Your let's chat heading should be on the middle of the page but it is on the left of it kindly make changes and make less spacing to it.
- [ ] I would suggest you to add same font-family and same color for you `p` tag.
### your design
![hisss](https://user-images.githubusercontent.com/81727988/171836023-80e4cf79-aca3-4267-8031-cf696c390a67.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/171836109-88fb7491-ae3b-4f67-ac72-4e531f387573.png)

2022-06-03 10:26 UTC, roshan-bajgain commented on index.html
> +        <button class="button-submit" type="submit">Send</button>
- [ ] Kindly remove the black border for this buttons and make the text color white as Figma design.
### your design
![his](https://user-images.githubusercontent.com/81727988/171836571-a4eabd34-ef71-470b-a9e9-0778dd9bb3ce.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/171836596-caf22f5b-d1c4-42c5-9116-cf9261b856e0.png)

2022-06-03 23:02 UTC, OmarRamoun requested changes
# 🟡 Just One More Thing 🔸

## Hi @PNdunguMaina 👋

Great work on making the changes requested by a previous reviewer 👏.

You've done well implementing some of the requested changes 💯, but **there are still some which aren't addressed yet**.

Though, There are some **few** issues 🐛 that you still need to work 🔧 on to go to the next project ⏭️ but you are almost there! 🏃

## Don't Feel frustrated 🤔

I am sure you worked hard 🛠️ to make these changes and actually you have to be proud of them 🥇.

And I understand how much you wanted to get this project approved ✔️ (I was at your place one day 😉). But, don't worry, You still can do it! 💪.

Just apply the changes ♻️ down below 👇 and this time it is going to be approved ✅. Just make sure that you **don't miss any of the changes** requested or introduce any **new bugs** 🐛.

> **Note:** A good tip is to check the box next to every change after you implement it ☑️. And you can also check the full website to see if it is still working after you have implemented the changes.

*Please, reach to [me](#thank-you-for-your-time-🙏-and-call-me-if-you-need-help-or-clarification-☎️) for any help 🪝 or any question ❓. I am always happy to help you 😃.*

## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 23:02 UTC, OmarRamoun commented on index.html
> +    <meta charset="UTF-8" />
- [ ] [REQUIRED] Please, make sure that the mobile version is working properly. You have a huge scrollbar down there.

![image](https://user-images.githubusercontent.com/60979926/171964851-af9ac547-cdab-483a-b0b8-1c41ef731296.png)

2022-06-04 12:12 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions
- [ **OPTIONAL** ] I think it would be better to wrap all your images in one folder(e.g.: images/) to make your root directory be more clear and more organized.
- [ **OPTIONAL** ] What do you think if you improve your **README** by adding a description of your project which can help users know what is about your project. And if possible, kindly complete other empty sections or remove those that don't related to your project to make documentation professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 12:12 UTC, tresorsawasawa commented on index.html
> +</html>
- [ **REQUIRED** ] Great job by making some changes required by the previous reviewer. So, I noticed that your project **doesn't work on the mobile version** as said by the **Previous reviewers**. It only works on the Desktop version. 
To be clear, your project is supposed to work properly both for the mobile and desktop versions. That means it should be responsive by using `@media query` as required for the project like:
```bash
@media screen and (min-width: 768px) {
   /*
    .
    .
  */
 }
```
When you have a screen less than **768px** in width, it would display the **Mobile version** otherwise, it would display the **Desktop** version. I suggest you click **[here](https://www.youtube.com/watch?v=lAOkx2yZESY)** to see how is a responsive webpage.
#### Here is how looks your project in the mobile version
![responsive](https://user-images.githubusercontent.com/83042742/171998047-7892a8e9-c54b-46fd-a348-ca55e4dda277.gif)

2022-06-09 09:41 UTC, Mihndim2020 requested changes
### Hi @PNdunguMaina, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages.
:heavy_check_mark: Great job with UI.

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments below and under the review._

#### I will leave the comments here, since your `Readme file` is not accessible for this `PR` as you did not make any change on it ####

- [ ] Please kindly update your `readme file` to reflect the changes for this milestone as this will make your `readme file` more informative and professional. It's a good thing you're using the [Microverse readme template](https://github.com/microverseinc/readme-template), but please adapt it to your project. Replace all the information in the various sections of the template with information pertaining to you and this project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 11:10 UTC, muneebulrehman approved these changes
Hi @PNdunguMaina , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳 
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Good follow-up with previous reviewers.
- Good PR description
- Good commit messages.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 11:14 UTC, merged